### ISSUE TITLE
Query: usage with KVM?

### ISSUE THREAD

**Issue by gurkanwal** [sdnfv/openNetVM#13]
Hi all,

Can the current setup designed for containers be extended for inter-VM communication using KVM?

Thanks and Regards,
Gurkanwal Singh

**Comment by twood02** [comment]
ONVM relies on DPDK's multi-process support: http://dpdk.org/doc/guides-16.07/prog_guide/multi_proc_support.html

That works across containers (as long as huge pages are set up appropriately), but as far as I know there is no support for KVM.

Our [original NetVM](https://www.usenix.org/node/179740) prototype used KVM, so it is possible to do, but rather inconvenient because of the difficulty sharing memory across protection boundaries.
