### ISSUE TITLE
rte_eth_dev_configure() exiting with code -22

### ISSUE THREAD

**Issue by asvcer** [sdnfv/openNetVM#19]
Hello, I encountered a problem when running onvm. When the program is initializing port 0, it always fail.

I think there must be something wrong with my configuration. Because when I run dpdk example -- distributor, it fails in initializing port 0, too. It shows that `ethdev port_id=0 nb_tx_queues=2 > 1`. It shows that my `port_conf` has `max_tx_queues=1`. Would you like to tell me what is the difference between NIC and PORT? I'm confused about that.

I run onvm in virtualbox, so that I encounter above problem. When I run onvm in a physical server, everything goes well, fortunately. ;)

By the way, how can I enable openNetVM to show more debug messages? I try to modify files in `$RTE_SDK/config/`, but it doesn't work.

Would you like to help me? Any suggestion is appreciated. Thank you very much.

**Comment by twood02** [comment]
Since this only appears in virtual box, I suspect the NIC driver being exposed to DPDK has some compatibility issues. We haven't tested ONVM in such an environment so you'll have to check with DPDK users to see if they can help.

I will close this issue since it appears to be a DPDK not ONVM problem, but if you do fine a solution, please post it here so others can benefit!

**Comment by asvcer** [comment]
Dear Tim,

Thank you for your reply. The NIC driver is okay. However, There only one ports on the driver while ONVM needs more than one ports. That is the cause.

Yours,
Shuo.
