### ISSUE TITLE
Linter Cppcheck. 

### ISSUE THREAD

**Issue by bdevierno1** [sdnfv/openNetVM#284]
## Bug Report

**Current Behavior**
Current [installation script](https://github.com/sdnfv/openNetVM/blob/master/style/install-linters.sh) for *cppcheck* is failing after update to ubuntu 20. 

**Environment**

- OS:  Ubuntu 20

**Possible Solution**

[Update the yaml file to specify ubuntu 20 instead of latest](https://github.com/sdnfv/openNetVM/blob/master/.github/workflows/Linter.yml#L7)
Update installation script for correct installation of cppcheck.

Output for cppcheck may differ depending on the version. Ensure the current [python linter parsing script](https://github.com/sdnfv/openNetVM/blob/master/style/run-lint.py) returns expected output.

**Comment by menglander2019** [comment]
I can take care of this once I get ubuntu-20 or a cloudlab account

**Comment by twood02** [comment]
I suggest we make two changes for this.

First, instead of using `runs-on: ubuntu-latest`, we should force it to use `ubuntu-20.04`. This won't actually fix the current issue (since ubuntu-latest == ubuntu-20.04 which is causing the whole problem), but it will ensure that we have a consistent environment and doesn't automatically change just because GitHub adds support for a newer version of Ubuntu.

Second, we need to fix the cppcheck instatllation. Right now we use `sudo apt-get install cppcheck=1.82-1` to install a particular version. This is giving an error because that version isn't supported by Ubuntu 20.04.  It looks like we should be able to use `2.1-1` based on [this page](https://packages.ubuntu.com/search?keywords=cppcheck).

**Comment by twood02** [comment]
resolved by #306
