### ISSUE TITLE
Some problem about packet speed

### ISSUE THREAD

**Issue by luzhang92** [sdnfv/openNetVM#41]
When I run the example application basic_monitor, the NF finish the function that send the packets it received out the system. 
In my understanding, the packet receive through the port, then send to the basic_monitor's RX,then to the basic_monitor's TX, and lastly, send out through the NIC TX. But, when I run the application, I saw that, the basic_monitor's RX and TX are the same rate with about 1488345 pkt/s, however, the NIC RX and TX are the same number with about 1488455 pkt/s.
It seems that the packet send out the system directly not through the basic_monitor? and why the NIC TX is larger than the NF's RX and TX?

**Comment by twood02** [comment]
The basic monitor NF is used to mirror packets back out the ports they arrive on.  For each packet it receives, the NF will swap the packet's src/dest MAC addresses and then send it back out the packet that it arrived on:

https://github.com/sdnfv/openNetVM/blob/develop/examples/basic_monitor/monitor.c#L160-L174

The behavior you are reporting sounds correct. The packets are arriving on the NIC RX, going to basic_monitor RX, going out basic_monitor TX when it finishes with them, and then going out the NIC TX to leave the system.

A typical use of basic monitor is to combine it with a tool like PktGen.  If you have pktgen send packets to a basic_monitor, it will mirror all of the packets back.  If this is working correctly, then the TX (outgoing) and RX (incoming) speeds on pktgen should be equivalent.

**Comment by twood02** [comment]
also, the numbers may be slightly different because of timing errors (the interval for NIC RX and NIC TX may be slightly different depending on OS scheduling, so they won't be identical)

**Comment by luzhang92** [comment]
hello professor, I also have a little problem, when I run two network NF, such as simple_forward as NF1 and basic_monitor as NF2, and the make the chain, NF1->NF2.
Now, I make a simple test, that I limit the cpu resource pinned to the NF1, such as 50% cpu to the NF1, and in this case, the NF1'rx drops some packets. I think it's normal, however, focus on the NF2(the cpu pinned with NF2 is 100% not limited). I saw the NF2's rx and tx is the same with NF1'rx. however, the packets_rate send to NIC'rx seems dropped much larger than the NF2/rx and tx.

It's a normal situation?

**Comment by twood02** [comment]
If you give NF1 50% CPU availability, it is becoming the bottleneck in your chain, and will reduce the rate of packets seen at NF2.

In addition, if NF1 has insufficient resources to process the arrival rate from the NIC, this will cause packets to be dropped when the NF's RX queue overflows.  We have seen some cases where excessive drops like this end up causing unexpectedly bad performance because it is wasteful to receive a packet only to drop it/free its memory.  This might be what you are seeing if the NIC RX is low.  You may be able to improve this by increasing the number of mbufs and the ring sizes so that more packets are buffered.

You can find some more information about this problem in our SIGCOMM 2017 paper: http://faculty.cs.gwu.edu/timwood/papers/17-SIGCOMM-NFVNice.pdf

**Comment by luzhang92** [comment]
yes, it's an interesting problem. 
Sorry to bother you, I also have a question when I use the openNetVM.
I run several functions which one function with one container and specific core as NIC->NF1->NF2->NF3.. . 
When I change the resource such as cpu utlization of the NF1, the NF1's rx will drop some packet( it's normal and I can understand). but I also saw the  NIC'tx or other NF's rx may drop packets. To my understanding, The specific core poll the ring for the specific NF and the NIC'tx. So, If I only change the resource of the NF1, the performance of other NF will not be influenced.

**Comment by twood02** [comment]
Here's an example:
```
1 million packets per second arrive at the NIC RX and are sent to NF1
NF1 has limited CPU resources, so it drops 500K of the incoming packets before sending to NF2
500K pps arrive at NF2, it has full resources to handle this load and sends to NF3
500K pps arrive at NF3, it sends to NIC TX and 500K pps leave the system.
```

That is the ideal case of what should happen.  If you are having mbuf pool size problems, then you might see this case:
```
1 Mpps arrive at NIC, but there aren't free buffers, so only 800K are received and sent to NF1
NF1 has limited CPU resources, so it drops 500K of the incoming packets before sending to NF2
300K pps arrive at NF2, it has full resources to handle this load and sends to NF3
300K pps arrive at NF3, it sends to NIC TX and 300K pps leave the system.
```

However, ONVM is not really well designed for adjusting the CPU resources in this way. It assumes each thread can use polling and get 100% of the CPU.  You may be getting odd behavior because of this.  For example, if some of the DPDK code has locks then if your NF1 takes a lock and then is descheduled that will cause performance issues. I don't think DPDK has any locks, but there might be other similar problems.

If you really want to have NFs with limited resources so that they can share CPUs, then you can try the experimental shared cpu branch: https://github.com/sdnfv/openNetVM/tree/experimental/shared_cpu

This code contains the hybrid polling/interrupt system described in our [CoNext Flurries paper](http://faculty.cs.gwu.edu/timwood/papers/16-CoNext-flurries.pdf)

**Comment by luzhang92** [comment]
Thank you very much. 
I will read and learn the paper and more about the NFV.

**Comment by twood02** [comment]
If you have further questions you can reopen this issue.
