### ISSUE TITLE
Message Passing between NFs

### ISSUE THREAD

**Issue by adityadhakal** [sdnfv/openNetVM#44]
How can I pass a message between two NFs?

I see there are two functions,

first one in onvm_mgr/onvm_nf.h

**int onvm_nf_send_msg(uint16_t dest, uint8_t msg_type, void *msg_data);**

and next one in onvm_nflib/onvm_nflib.h

**int onvm_nflib_handle_msg(struct onvm_nf_msg *msg);**

However, they seem to be apparatus for just ONVM manager to NF communication, how can I communicate between two NFs?

Do we already have functions that I can pass a certain message to certain NF and the destination NF will automatically process the message?

Thank you,
Aditya

**Comment by twood02** [comment]
Those functions are only designed for sending/receiving messages between the manager and an NF. We currently do not have functions in place to support NF->NF messaging.

Here are two options to resolve this:

1) Have the sender NF create an mbuf packet and fill in the data you want to send in the packet payload. Set the recipient NF as the destination and use the To NF action to send to it. You might want to set a bit in the meta data structure so that your recipient NF can distinguish between incoming network packets and incoming "message" packets.  See the Speed Tester NF for an example of creating packets, setting meta bits, and returning the packet for transmission.

2) Use the two functions you listed above to have an NF send a message to the manager and then have the manager interpret that and send it to the destination NF.  This is probably more difficult than option 1.

If one of these options will work for you, then you can close this issue.

**Comment by adityadhakal** [comment]
Thank you Tim, 1 seems like the easiest way to send a message now.
