### ISSUE TITLE
Speed Tester - tx rate control

### ISSUE THREAD

**Issue by lilishan9248** [sdnfv/openNetVM#45]
Hi, 

I have noticed that the new version of speed tester adds the function of latency measurement. Now, I want to measure the process latency of another NF using the speed tester, which sends some sample packets to the NF. However, the current speed tester NF repeatedly sending that batch of packets to itself or another NF. 

So, how can I control the transition rate of speed tester? One way is to delay some time after sending a batch of packets by function rte_delay_us(unsigned us). But after reading the code of speed tester, I have no idea why the speed tester repeatedly sending packets? And how to adds rte_delay_us to limit the transition rate?

Lishan

**Comment by twood02** [comment]
Currently we do not have a way to generate packets at a configurable rate.   First, here is an explanation of how the speed tester works. It starts by [creating a batch of packets](https://github.com/sdnfv/openNetVM/blob/cbef28396538f434ee72932eb4ac3741190e4b2a/examples/speed_tester/speed_tester.c#L406) in its main function. It then sends these packets to a destination NF.  If you configure your NFs in a loop, that means the original batch of packets will keep circulating forever.  Speed tester measures the speed that these packets circulate. 

There are a couple methods you could use to have packets arrive at a configurable rate.

0. Have an external packet generator (moongen) measure latency. This is the simplest solution, but it will include full end-to-end latency, not just your NF's processing.

1. Use an external packet generator but measure latency locally. Have incoming packets go through a chain like: Speed Tester -> test NF -> Speed Tester -> DROP (only run a single instance of speed tester).  When you run the speed tester, use the `-c` flag to have it create 0 packets (currently it requires this flag to be 1 or greater, so change [this line to allow 0](https://github.com/sdnfv/openNetVM/blob/cbef28396538f434ee72932eb4ac3741190e4b2a/examples/speed_tester/speed_tester.c#L170)). You will also need to modify the speed tester so that the second time it gets a packet and measures the latency it will drop the packet instead of sending it to the destination NF (or you could have it send the packet out the NIC if you prefer).  You also will need to change [this line ](https://github.com/sdnfv/openNetVM/blob/cbef28396538f434ee72932eb4ac3741190e4b2a/examples/speed_tester/speed_tester.c#L256) so that speed tester won't ignore packets which don't have the correct meta data bits set in them.

2. Create a simple packet generator NF. You could create an NF that sends at a controlled rate by using support for a [callback handler](https://github.com/sdnfv/openNetVM/blob/27b588bfa1aae4195c0ac9bca4a05216fd1b889f/onvm/onvm_nflib/onvm_nflib.h#L83-L98). The NF will call this handler function every run loop (after processing an incoming batch of packets if any are available). You could have your callback check the current time and if enough time has elapsed it could create a batch of packets and send them out.  You could combine this with option 1 above and have speed tester measure latency, or you could make your own generator write time stamps when it creates a packet and measure elapsed time when your test NF sends the packet back to it.  See the Speed Tester NF for code to create packets / measure time, and see the [Flow Tracker](https://github.com/sdnfv/openNetVM/blob/cbef28396538f434ee72932eb4ac3741190e4b2a/examples/flow_tracker/flow_tracker.c#L278) for an example of using callbacks.  You do not want to use the delay function you mentioned because that would cause the NF to busy wait, preventing it from receiving packets coming back to it.

Eventually we plan to implement option # 2 as a new NF or an extension to speed tester.  If you write the code please consider contributing it back with a pull request!

If these options work for you, please close this issue.

**Comment by twood02** [comment]
Also, be aware that the way the speed tester records timing info is [by writing at the end of the packet](https://github.com/sdnfv/openNetVM/blob/cbef28396538f434ee72932eb4ac3741190e4b2a/examples/speed_tester/speed_tester.c#L262). This may cause problems with the NF you are trying to test.

**Comment by lilishan9248** [comment]
Another problem is the computing of the old_time in line https://github.com/sdnfv/openNetVM/blob/cbef28396538f434ee72932eb4ac3741190e4b2a/examples/speed_tester/speed_tester.c#L262

According to what I understand, the old_time is used to record the transmit time of the packet. 
However, the function  rte_pktmbuf_mtod is used to obtain a macro that points to the pkt.

**Comment by twood02** [comment]
Yes, it assumes that space was allocated for this time stamp when the packet was first created by speed tester here: https://github.com/sdnfv/openNetVM/blob/cbef28396538f434ee72932eb4ac3741190e4b2a/examples/speed_tester/speed_tester.c#L434

**Comment by lilishan9248** [comment]
So, you mean that: when the packet was created, the space is allocated to the timestamp and the packet transmission time is recorded in this space? Right? 
However, I have not noticed which line record the packet transmission time.

**Comment by twood02** [comment]
when it is created the timestamp is set to 0 (really it should be set to the current clock, but this just means the latency measurement in the first interval is wrong, after that it will be OK).

The timestamp is updated when the packet is next seen at line 267:
https://github.com/sdnfv/openNetVM/blob/cbef28396538f434ee72932eb4ac3741190e4b2a/examples/speed_tester/speed_tester.c#L262-L267

From then on the same packets will cycle, and the old time stamp will be updated each time the speed tester sees the packet again.

**Comment by lilishan9248** [comment]
Got it. Thanks a lot!

**Comment by lilishan9248** [comment]
I have implemented the NF's latency measurement works by your above suggested method 1. 
However, it is difficult to check which time the speed tester receives the packet? How to distinguish the first time and the second time?
