### ISSUE TITLE
Manager crashes in the modified openNetVM code (supporting parallelism) for large number of packets

### ISSUE THREAD

**Issue by madhura-a** [sdnfv/openNetVM#51]
Hi,
I have modified the openNetVM code to support parallelism. The code is working fine when a number of packets transmitted through the chain are low, say 100 or 1000. When I try to send more number of packets (more than 5000), manager crashes. I tried debugging the code, I found that the manager crashes while executing the function "onvm_pkt_flush_port_queue". Can you please tell me what could be the reason for this behavior?

**Comment by madhura-a** [comment]
Actually, In my code, I have defined my own metadata(64 bit) which includes fields like matchID, version, packetNumber. The next network function to which the packet has to be forwarded is decided by the constructed service graph. Is defining own metadata is causing the issue?

**Comment by twood02** [comment]
I don't know why that would cause the issue, but it depends where you are storing that data. If you are keeping it in the mbuf perhaps you overwrote some of dpdk's meta data?  ONVM uses the `userdata` field in the mbuf, so if you try to use that space too it will also cause a conflict.

**Comment by madhura-a** [comment]
I have used `userdata` field only to define the metadata and I have commented out onvm metadata. Will it still cause a conflict?

**Comment by twood02** [comment]
This will break a lot of the existing code in the NF Manager TX threads and nflib -- the NFs use that space to specify what actions they want to happen next.  If you have rewritten this code to handle parallelism it may be OK.

We often find it simplest to evaluate these changes using artificial packets instead of real network traffic.  You might try verifying whether your parallelism code works correctly when a Speed Tester NF creates packets (either fake packets or by reading a pcap file). Have it send through a set of parallel NFs and then either drop the packets or send them back to speed tester to create an infinite loop.  That will help you verify that your parallelism logic is correct without worrying about packet memory management from creating/freeing packets received/sent on the NIC.

**Comment by madhura-a** [comment]
It is working fine now. Thank you for your response.
