### ISSUE TITLE
How does openNetVM pull packets from NIC and send to an NF?

### ISSUE THREAD

**Issue by omzmarlon** [sdnfv/openNetVM#63]
Hi there,

I'm wondering after a NIC receives a packet from a remote host, how does ONVM decide which first NF to forward this packet to?

So for example, if I set up a chain that looks like: simple_forwarder -> basic_monitor, where I want simple_forwarder to be the "gateway" NF into my chain. How do I tell ONVM to send all the NIC packets to simple_forwarder instead of basic_monitor? (Or how does ONVM even know it should forward a NIC packet to a NF? Does it do it by default?)

Thanks

**Comment by twood02** [comment]
When an RX thread receives a packet from the NIC it first does a flow table lookup to see if there is a rule for that specific flow.  If no rule is found, then the "default service chain" is applied.  The default chain is just "send to NF with service ID 1", but you could change this if you want.

This PR has some information related to this:
https://github.com/sdnfv/openNetVM/issues/62
We would like to make this easier for most users (since they might not need the flow table lookup) and we currently do not have good examples for how to either set flow table rules or the default chain.

**Comment by koolzz** [comment]
Same answer as @twood02, with code links

When packets arrive from the NIC they are [received by an RX thread](https://github.com/sdnfv/openNetVM/blob/develop/onvm/onvm_mgr/main.c#L172). The destination for packets from the NIC is [based on the flow table lookup](https://github.com/sdnfv/openNetVM/blob/fcac247f2f6a8106480ca8d50a6b7b73e0c7f31e/onvm/onvm_mgr/onvm_pkt.c#L74:). 
If a custom flowtable wasn't setup, ONVM will use the [default service chain](https://github.com/sdnfv/openNetVM/blob/fcac247f2f6a8106480ca8d50a6b7b73e0c7f31e/onvm/onvm_mgr/onvm_init.c#L243). This means the action will be ONVM_NF_ACTION_TONF and the NF to send to will be 1, which is why by default it wil simply arrive at the first NF.

**Comment by omzmarlon** [comment]
I see. Clears my confusion. Thanks!

**Comment by Balaram6712** [comment]
Hi there,
Can anyone help me out how I can set up 2 default chains and based on the port which the packet was received I can forward the packet based on the port to the chain.

**Comment by Balaram6712** [comment]
> When an RX thread receives a packet from the NIC it first does a flow table lookup to see if there is a rule for that specific flow. If no rule is found, then the "default service chain" is applied. The default chain is just "send to NF with service ID 1", but you could change this if you want.
> 
> This PR has some information related to this:
> #62
> We would like to make this easier for most users (since they might not need the flow table lookup) and we currently do not have good examples for how to either set flow table rules or the default chain.

Hi,
Is it possible to set up 2 default chains when using 2 ports, forward the packet based on the port on which it arrives to a corresponding default chain? Could you please give some insights on how we can do so? 

Thanks
